-- ============================================
-- SUPABASE DATABASE SCHEMA FOR PORTFOLIO
-- Safe for existing tables - checks columns first
-- Run this in Supabase SQL Editor
-- ============================================

-- ============================================
-- 1. VISITORS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS visitors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  count INTEGER DEFAULT 0 NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM visitors) THEN
    INSERT INTO visitors (count) VALUES (12840);
  END IF;
END $$;

-- ============================================
-- 2. SKILLS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS skills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  icon TEXT,
  level INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM skills) THEN
    INSERT INTO skills (name, category, level) VALUES
    ('JavaScript', 'Frontend', 80),
    ('TypeScript', 'Frontend', 75),
    ('React', 'Frontend', 70);
  END IF;
END $$;

-- ============================================
-- 3. PROJECTS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  stack TEXT,
  tag TEXT,
  image TEXT,
  github TEXT,
  live TEXT,
  featured BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM projects) THEN
    INSERT INTO projects (title, description, stack, tag, github, live, featured)
    VALUES ('Portfolio', 'Personal portfolio website', 'React, Tailwind, Vercel', 'Web', 'https://github.com/netra-portfolio', 'https://netra.me', true);
  END IF;
END $$;

-- ============================================
-- 4. EXPERIENCES TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS experiences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company TEXT NOT NULL,
  role TEXT,
  period TEXT,
  description TEXT,
  current BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE experiences ADD COLUMN IF NOT EXISTS company TEXT;
ALTER TABLE experiences ADD COLUMN IF NOT EXISTS role TEXT;
ALTER TABLE experiences ADD COLUMN IF NOT EXISTS period TEXT;
ALTER TABLE experiences ADD COLUMN IF NOT EXISTS current BOOLEAN DEFAULT false;

DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM experiences) THEN
    INSERT INTO experiences (company, role, period, description, current)
    VALUES ('Bharati Vidyapeeth University', 'BCA Student', '2025 - 2028', 'Building core foundations in computer applications.', true);
  END IF;
END $$;

-- ============================================
-- 5. BLOGS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS blogs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  content TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE blogs ADD COLUMN IF NOT EXISTS content TEXT;

DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM blogs) THEN
    INSERT INTO blogs (title, slug, content)
    VALUES ('Designing Motion That Feels Expensive', 'designing-motion', 'Exploring animation techniques that create premium user experiences.');
  END IF;
END $$;

-- ============================================
-- 6. CERTIFICATES TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS certificates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  issuer TEXT NOT NULL,
  url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE certificates ADD COLUMN IF NOT EXISTS url TEXT;

DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM certificates WHERE name = 'Buildathon 2025') THEN
    INSERT INTO certificates (name, issuer, url)
    VALUES ('Buildathon 2025', 'Unstop', 'https://unstop.com');
  END IF;
END $$;

-- ============================================
-- 7. TESTIMONIALS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS testimonials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT,
  content TEXT,
  avatar TEXT,
  featured BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE testimonials ADD COLUMN IF NOT EXISTS content TEXT;
ALTER TABLE testimonials ADD COLUMN IF NOT EXISTS featured BOOLEAN DEFAULT false;

DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM testimonials) THEN
    INSERT INTO testimonials (name, role, content, featured)
    VALUES ('Learning Focus', 'Student Portfolio', 'Curious, consistent, and building practical projects.', true);
  END IF;
END $$;

-- ============================================
-- 8. CONTACTS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  message TEXT NOT NULL,
  read BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE contacts ADD COLUMN IF NOT EXISTS read BOOLEAN DEFAULT false;

-- ============================================
-- 9. STATS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS stats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label TEXT NOT NULL,
  value INTEGER NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM stats) THEN
    INSERT INTO stats (label, value) VALUES ('Projects Completed', 15);
  END IF;
END $$;

-- ============================================
-- 10. LINKEDIN POSTS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS linkedin_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  url TEXT,
  category TEXT DEFAULT 'Achievement',
  date TEXT,
  body TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- ENABLE REALTIME (skip if already enabled)
-- ============================================
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND tablename = 'visitors'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE visitors;
  END IF;
END $$;

-- ============================================
-- TRIGGER FUNCTION
-- ============================================
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_visitors_updated_at ON visitors;
CREATE TRIGGER update_visitors_updated_at BEFORE UPDATE ON visitors
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ============================================
-- ROW LEVEL SECURITY
-- ============================================

ALTER TABLE visitors ENABLE ROW LEVEL SECURITY;
ALTER TABLE skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE experiences ENABLE ROW LEVEL SECURITY;
ALTER TABLE blogs ENABLE ROW LEVEL SECURITY;
ALTER TABLE certificates ENABLE ROW LEVEL SECURITY;
ALTER TABLE testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE linkedin_posts ENABLE ROW LEVEL SECURITY;

-- ============================================
-- CLEAR OLD POLICIES
-- ============================================

DO $$ 
BEGIN
  DROP POLICY IF EXISTS "Anyone can read visitors" ON visitors;
  DROP POLICY IF EXISTS "Admins can update visitors" ON visitors;
  DROP POLICY IF EXISTS "Service role can insert visitors" ON visitors;
  
  DROP POLICY IF EXISTS "Anyone can read skills" ON skills;
  DROP POLICY IF EXISTS "Anyone can insert skills" ON skills;
  DROP POLICY IF EXISTS "Anyone can update skills" ON skills;
  DROP POLICY IF EXISTS "Anyone can delete skills" ON skills;
  
  DROP POLICY IF EXISTS "Anyone can read projects" ON projects;
  DROP POLICY IF EXISTS "Anyone can insert projects" ON projects;
  DROP POLICY IF EXISTS "Anyone can update projects" ON projects;
  DROP POLICY IF EXISTS "Anyone can delete projects" ON projects;
  
  DROP POLICY IF EXISTS "Anyone can read experiences" ON experiences;
  DROP POLICY IF EXISTS "Anyone can insert experiences" ON experiences;
  DROP POLICY IF EXISTS "Anyone can update experiences" ON experiences;
  DROP POLICY IF EXISTS "Anyone can delete experiences" ON experiences;
  
  DROP POLICY IF EXISTS "Anyone can read blogs" ON blogs;
  DROP POLICY IF EXISTS "Anyone can insert blogs" ON blogs;
  DROP POLICY IF EXISTS "Anyone can update blogs" ON blogs;
  DROP POLICY IF EXISTS "Anyone can delete blogs" ON blogs;
  
  DROP POLICY IF EXISTS "Anyone can read certificates" ON certificates;
  DROP POLICY IF EXISTS "Anyone can insert certificates" ON certificates;
  DROP POLICY IF EXISTS "Anyone can update certificates" ON certificates;
  DROP POLICY IF EXISTS "Anyone can delete certificates" ON certificates;
  
  DROP POLICY IF EXISTS "Anyone can read testimonials" ON testimonials;
  DROP POLICY IF EXISTS "Anyone can insert testimonials" ON testimonials;
  DROP POLICY IF EXISTS "Anyone can update testimonials" ON testimonials;
  DROP POLICY IF EXISTS "Anyone can delete testimonials" ON testimonials;
  
  DROP POLICY IF EXISTS "Anyone can read contacts" ON contacts;
  DROP POLICY IF EXISTS "Anyone can insert contacts" ON contacts;
  DROP POLICY IF EXISTS "Anyone can update contacts" ON contacts;
  DROP POLICY IF EXISTS "Anyone can delete contacts" ON contacts;
  
  DROP POLICY IF EXISTS "Anyone can read stats" ON stats;
  DROP POLICY IF EXISTS "Anyone can insert stats" ON stats;
  DROP POLICY IF EXISTS "Anyone can update stats" ON stats;
  DROP POLICY IF EXISTS "Anyone can delete stats" ON stats;
END $$;

-- ============================================
-- CREATE NEW POLICIES
-- ============================================

-- LINKEDIN POSTS
CREATE TABLE IF NOT EXISTS linkedin_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  url TEXT,
  category TEXT DEFAULT 'Achievement',
  date TEXT,
  body TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE linkedin_posts ADD COLUMN IF NOT EXISTS url TEXT;
ALTER TABLE linkedin_posts ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'Achievement';
ALTER TABLE linkedin_posts ADD COLUMN IF NOT EXISTS date TEXT;
ALTER TABLE linkedin_posts ADD COLUMN IF NOT EXISTS body TEXT;

-- VISITORS
CREATE POLICY "Anyone can read visitors" ON visitors FOR SELECT USING (true);
CREATE POLICY "Admins can update visitors" ON visitors FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Service role can insert visitors" ON visitors FOR INSERT WITH CHECK (auth.role() = 'service_role');

-- SKILLS
CREATE POLICY "Anyone can read skills" ON skills FOR SELECT USING (true);
CREATE POLICY "Anyone can insert skills" ON skills FOR INSERT WITH CHECK (true);
CREATE POLICY "Anyone can update skills" ON skills FOR UPDATE USING (true);
CREATE POLICY "Anyone can delete skills" ON skills FOR DELETE USING (true);

-- PROJECTS
CREATE POLICY "Anyone can read projects" ON projects FOR SELECT USING (true);
CREATE POLICY "Anyone can insert projects" ON projects FOR INSERT WITH CHECK (true);
CREATE POLICY "Anyone can update projects" ON projects FOR UPDATE USING (true);
CREATE POLICY "Anyone can delete projects" ON projects FOR DELETE USING (true);

-- EXPERIENCES
CREATE POLICY "Anyone can read experiences" ON experiences FOR SELECT USING (true);
CREATE POLICY "Anyone can insert experiences" ON experiences FOR INSERT WITH CHECK (true);
CREATE POLICY "Anyone can update experiences" ON experiences FOR UPDATE USING (true);
CREATE POLICY "Anyone can delete experiences" ON experiences FOR DELETE USING (true);

-- BLOGS
CREATE POLICY "Anyone can read blogs" ON blogs FOR SELECT USING (true);
CREATE POLICY "Anyone can insert blogs" ON blogs FOR INSERT WITH CHECK (true);
CREATE POLICY "Anyone can update blogs" ON blogs FOR UPDATE USING (true);
CREATE POLICY "Anyone can delete blogs" ON blogs FOR DELETE USING (true);

-- CERTIFICATES
CREATE POLICY "Anyone can read certificates" ON certificates FOR SELECT USING (true);
CREATE POLICY "Anyone can insert certificates" ON certificates FOR INSERT WITH CHECK (true);
CREATE POLICY "Anyone can update certificates" ON certificates FOR UPDATE USING (true);
CREATE POLICY "Anyone can delete certificates" ON certificates FOR DELETE USING (true);

-- TESTIMONIALS
CREATE POLICY "Anyone can read testimonials" ON testimonials FOR SELECT USING (true);
CREATE POLICY "Anyone can insert testimonials" ON testimonials FOR INSERT WITH CHECK (true);
CREATE POLICY "Anyone can update testimonials" ON testimonials FOR UPDATE USING (true);
CREATE POLICY "Anyone can delete testimonials" ON testimonials FOR DELETE USING (true);

-- CONTACTS
CREATE POLICY "Anyone can read contacts" ON contacts FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can insert contacts" ON contacts FOR INSERT WITH CHECK (true);
CREATE POLICY "Anyone can update contacts" ON contacts FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can delete contacts" ON contacts FOR DELETE USING (auth.role() = 'authenticated');

-- STATS
CREATE POLICY "Anyone can read stats" ON stats FOR SELECT USING (true);
CREATE POLICY "Anyone can insert stats" ON stats FOR INSERT WITH CHECK (true);
CREATE POLICY "Anyone can update stats" ON stats FOR UPDATE USING (true);
CREATE POLICY "Anyone can delete stats" ON stats FOR DELETE USING (true);

-- LINKEDIN POSTS
CREATE POLICY "Anyone can read linkedin_posts" ON linkedin_posts FOR SELECT USING (true);
CREATE POLICY "Anyone can insert linkedin_posts" ON linkedin_posts FOR INSERT WITH CHECK (true);
CREATE POLICY "Anyone can update linkedin_posts" ON linkedin_posts FOR UPDATE USING (true);
CREATE POLICY "Anyone can delete linkedin_posts" ON linkedin_posts FOR DELETE USING (true);

SELECT 'Database setup complete!' as status;