-- Portfolio Database Schema for Supabase
-- Run this in Supabase SQL Editor

-- 1. Visitors counter table
CREATE TABLE IF NOT EXISTS visitors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  count INTEGER DEFAULT 0 NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO visitors (count) VALUES (12840);

-- 2. Skills table
CREATE TABLE IF NOT EXISTS skills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  icon TEXT,
  level INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Projects table
CREATE TABLE IF NOT EXISTS projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  stack TEXT,
  tag TEXT,
  image TEXT,
  github TEXT,
  live TEXT,
  featured BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Experience table
CREATE TABLE IF NOT EXISTS experiences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company TEXT NOT NULL,
  role TEXT NOT NULL,
  period TEXT,
  description TEXT,
  current BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Blog posts table
CREATE TABLE IF NOT EXISTS blogs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  content TEXT,
  excerpt TEXT,
  image TEXT,
  published BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Certificates table
CREATE TABLE IF NOT EXISTS certificates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  issuer TEXT NOT NULL,
  date DATE,
  url TEXT,
  credential_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Testimonials table
CREATE TABLE IF NOT EXISTS testimonials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT,
  company TEXT,
  content TEXT NOT NULL,
  avatar TEXT,
  featured BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Contact messages table
CREATE TABLE IF NOT EXISTS contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  message TEXT NOT NULL,
  read BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Stats table
CREATE TABLE IF NOT EXISTS stats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label TEXT NOT NULL,
  value INTEGER NOT NULL,
  icon TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE visitors;

-- Add updated_at trigger function
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers for updated_at
CREATE TRIGGER update_visitors_updated_at BEFORE UPDATE ON visitors
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ============================================
-- ROW LEVEL SECURITY POLICIES
-- ============================================

-- Enable RLS on all tables
ALTER TABLE visitors ENABLE ROW LEVEL SECURITY;
ALTER TABLE skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE experiences ENABLE ROW LEVEL SECURITY;
ALTER TABLE blogs ENABLE ROW LEVEL SECURITY;
ALTER TABLE certificates ENABLE ROW LEVEL SECURITY;
ALTER TABLE testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE stats ENABLE ROW LEVEL SECURITY;

-- ============================================
-- VISITORS POLICIES
-- ============================================
-- Anyone can read visitor count
CREATE POLICY "Anyone can read visitors" ON visitors FOR SELECT USING (true);
-- Only authenticated users can update visitor count
CREATE POLICY "Admins can update visitors" ON visitors FOR UPDATE USING (
  auth.role() = 'authenticated'
);
-- Only service role can insert
CREATE POLICY "Service role can insert visitors" ON visitors FOR INSERT WITH CHECK (
  auth.role() = 'service_role'
);

-- ============================================
-- SKILLS POLICIES
-- ============================================
-- Anyone can read skills
CREATE POLICY "Anyone can read skills" ON skills FOR SELECT USING (true);
-- Only authenticated users can insert
CREATE POLICY "Anyone can insert skills" ON skills FOR INSERT WITH CHECK (
  auth.role() = 'authenticated'
);
-- Only authenticated users can update
CREATE POLICY "Anyone can update skills" ON skills FOR UPDATE USING (
  auth.role() = 'authenticated'
);
-- Only authenticated users can delete
CREATE POLICY "Anyone can delete skills" ON skills FOR DELETE USING (
  auth.role() = 'authenticated'
);

-- ============================================
-- PROJECTS POLICIES
-- ============================================
-- Anyone can read projects
CREATE POLICY "Anyone can read projects" ON projects FOR SELECT USING (true);
-- Only authenticated users can insert
CREATE POLICY "Anyone can insert projects" ON projects FOR INSERT WITH CHECK (
  auth.role() = 'authenticated'
);
-- Only authenticated users can update
CREATE POLICY "Anyone can update projects" ON projects FOR UPDATE USING (
  auth.role() = 'authenticated'
);
-- Only authenticated users can delete
CREATE POLICY "Anyone can delete projects" ON projects FOR DELETE USING (
  auth.role() = 'authenticated'
);

-- ============================================
-- EXPERIENCES POLICIES
-- ============================================
-- Anyone can read experiences
CREATE POLICY "Anyone can read experiences" ON experiences FOR SELECT USING (true);
-- Only authenticated users can insert
CREATE POLICY "Anyone can insert experiences" ON experiences FOR INSERT WITH CHECK (
  auth.role() = 'authenticated'
);
-- Only authenticated users can update
CREATE POLICY "Anyone can update experiences" ON experiences FOR UPDATE USING (
  auth.role() = 'authenticated'
);
-- Only authenticated users can delete
CREATE POLICY "Anyone can delete experiences" ON experiences FOR DELETE USING (
  auth.role() = 'authenticated'
);

-- ============================================
-- BLOGS POLICIES
-- ============================================
-- Anyone can read published blogs
CREATE POLICY "Anyone can read published blogs" ON blogs FOR SELECT USING (true);
-- Anyone can read blogs (published or draft for preview)
CREATE POLICY "Anyone can read all blogs" ON blogs FOR SELECT USING (true);
-- Only authenticated users can insert
CREATE POLICY "Anyone can insert blogs" ON blogs FOR INSERT WITH CHECK (
  auth.role() = 'authenticated'
);
-- Only authenticated users can update
CREATE POLICY "Anyone can update blogs" ON blogs FOR UPDATE USING (
  auth.role() = 'authenticated'
);
-- Only authenticated users can delete
CREATE POLICY "Anyone can delete blogs" ON blogs FOR DELETE USING (
  auth.role() = 'authenticated'
);

-- ============================================
-- CERTIFICATES POLICIES
-- ============================================
-- Anyone can read certificates
CREATE POLICY "Anyone can read certificates" ON certificates FOR SELECT USING (true);
-- Only authenticated users can insert
CREATE POLICY "Anyone can insert certificates" ON certificates FOR INSERT WITH CHECK (
  auth.role() = 'authenticated'
);
-- Only authenticated users can update
CREATE POLICY "Anyone can update certificates" ON certificates FOR UPDATE USING (
  auth.role() = 'authenticated'
);
-- Only authenticated users can delete
CREATE POLICY "Anyone can delete certificates" ON certificates FOR DELETE USING (
  auth.role() = 'authenticated'
);

-- ============================================
-- TESTIMONIALS POLICIES
-- ============================================
-- Anyone can read testimonials
CREATE POLICY "Anyone can read testimonials" ON testimonials FOR SELECT USING (true);
-- Only authenticated users can insert
CREATE POLICY "Anyone can insert testimonials" ON testimonials FOR INSERT WITH CHECK (
  auth.role() = 'authenticated'
);
-- Only authenticated users can update
CREATE POLICY "Anyone can update testimonials" ON testimonials FOR UPDATE USING (
  auth.role() = 'authenticated'
);
-- Only authenticated users can delete
CREATE POLICY "Anyone can delete testimonials" ON testimonials FOR DELETE USING (
  auth.role() = 'authenticated'
);

-- ============================================
-- CONTACTS POLICIES
-- ============================================
-- Anyone can read contacts (can restrict later)
CREATE POLICY "Anyone can read contacts" ON contacts FOR SELECT USING (
  auth.role() = 'authenticated'
);
-- Anyone can submit contact form
CREATE POLICY "Anyone can insert contacts" ON contacts FOR INSERT WITH CHECK (true);
-- Only authenticated users can update (mark as read)
CREATE POLICY "Anyone can update contacts" ON contacts FOR UPDATE USING (
  auth.role() = 'authenticated'
);
-- Only authenticated users can delete
CREATE POLICY "Anyone can delete contacts" ON contacts FOR DELETE USING (
  auth.role() = 'authenticated'
);

-- ============================================
-- STATS POLICIES
-- ============================================
-- Anyone can read stats
CREATE POLICY "Anyone can read stats" ON stats FOR SELECT USING (true);
-- Only authenticated users can insert
CREATE POLICY "Anyone can insert stats" ON stats FOR INSERT WITH CHECK (
  auth.role() = 'authenticated'
);
-- Only authenticated users can update
CREATE POLICY "Anyone can update stats" ON stats FOR UPDATE USING (
  auth.role() = 'authenticated'
);
-- Only authenticated users can delete
CREATE POLICY "Anyone can delete stats" ON stats FOR DELETE USING (
  auth.role() = 'authenticated'
);

-- ============================================
-- ADMIN USER (create after running)
-- Run this separately to create an admin:
-- CREATE USER IF NOT EXISTS admin WITH PASSWORD 'your-secure-password';
-- GRANT authenticated TO admin;
-- ============================================

-- ============================================
-- SAMPLE DATA
-- ============================================

INSERT INTO skills (name, category, level) VALUES
  ('JavaScript', 'Languages', 95),
  ('Python', 'Languages', 90),
  ('React', 'Frontend', 95),
  ('Node.js', 'Backend', 88),
  ('TypeScript', 'Languages', 92);

INSERT INTO projects (title, description, stack, tag, github, live, featured) VALUES
  ('Portfolio', 'Personal portfolio website', 'React, Tailwind, Vercel', 'Web', 'https://github.com/netra-portfolio', 'https://netra.me', true);

INSERT INTO experiences (company, role, period, current) VALUES
  ('Tech Company', 'Software Developer', '2023 - Present', true);

INSERT INTO testimonials (name, role, company, content, featured) VALUES
  ('John Doe', 'CTO', 'Tech Corp', 'Great developer to work with!', true);

INSERT INTO stats (label, value) VALUES
  ('Projects Completed', 15),
  ('Years Experience', 3),
  ('Clients Served', 10);